// Automatically generated by astro-icon
// 4b04c1fdd5d7b8af948fa8363f6a4096b57f0b70dac1f31cb76dcf6ba2a0026f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "astrojs"
		| "contentful"
		| "figma"
		| "gsap"
		| "nextjs"
		| "react"
		| "sass"
		| "shopify"
		| "squarespace"
		| "styled-components"
		| "tailwindcss"
		| "typescript"
		| "webflow"
		| "wordpress";
}